server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }


    # =====================================================
    # Docker / Docker Compose Setup
    # =====================================================
    # Uncomment this block if you are running the project
    # using Docker Compose only.
    #
    # In this setup, Nginx acts as a reverse proxy and
    # forwards API requests to the backend container.
    #
    # For Kubernetes/EKS deployments, API routing is
    # handled by the NGINX Ingress Controller, so this
    # block should remain commented out.
    #
    
    # location /api/ {                          
    #     proxy_pass http://backend:3000;

    #     proxy_set_header Host $host;
    #     proxy_set_header X-Real-IP $remote_addr;
    #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #     proxy_set_header X-Forwarded-Proto $scheme;
    # }
}