services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./Backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
    - ./Backend/.env
    depends_on:
      - mongo

  frontend:
    build:
      context: ./Frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo-data:
