apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: hiresense
type: Opaque

stringData:
  MONGO_URI: "mongodb+srv://gauravsunil2005_db_user:fcFNBbzIphcFvwce@hiresenseai-cluster.wu75bjp.mongodb.net/hiresense-master"
  JWT_SECRET: "b199a24004283c39088621522a9f3562022193e7b57fc74566c7d327e685589a"
  GOOGLE_GENAI_API_KEY: "AQ.Ab8RN6KHBdq0g-sFB8DRcTS4A4mv8A_J0_W7FdcDhfbUDNtNyQ"