apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: hiresense
type: Opaque

stringData:
  MONGO_URI: "<mongodb-atlas-uri>"
  JWT_SECRET: "<jwt-secret>"
  GOOGLE_GENAI_API_KEY: "<google-genai-api-key>"